languageCode = "en"
languageName = "English"
weight = 1
title = "Harish Sheoran"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  #secondaryLogo = "img/me.jpg"
  description = "Harish Sheoran, Engineer."
  copyright = "&copy; 2025 Harish Sheoran"

[author]
  name = "Harish Sheoran"
  image = "img/profile.jpg"
  headline = "Engineer"
  bio = "Engineer"
  links = [
    { email = "mailto:harisheoran@protonmail.com" },
    { x-twitter = "https://twitter.com/harisheoran" },
    { linkedin = "https://linkedin.com/in/harisheoran" },
    { github = "https://github.com/harisheoran" },
    { gitlab = "https://gitlab.com/harisheoran" },
    { hashnode = "https://harisheoran.hashnode.dev" },
    { dev = "https://dev.to/harisheoran" },
    { youtube = "https://www.youtube.com/channel/UCkL3XhMfEA46NH57gVSb_Fw" },
    { rss = "https://harisheoran.github.io/index.xml"},
   ]
