languageCode = "en"
languageName = "English"
weight = 1
title = "Harish Sheoran"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/profile.jpg"
  secondaryLogo = "img/profile.jpg"
  description = "Harish Sheoran, Android Developer, Full Stack Developer"
  # copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "Harish Sheoran"
   image = "img/profile3.jpeg"
   headline = "Software Developer"
   bio = "Creating apps that make life a byte more interesting! 📱🌟"
   links = [
     { email = "mailto:harisheoran01@gmail.com" },
     { twitter = "https://twitter.com/harisheoran" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/harisheoran" },
     { gitlab = "https://gitlab.com/harisheoran" },
#     { google = "https://www.google.com/" },
     { hashnode = "https://harisheoran.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/harishsheoran01" },
     { mastodon = "https://mastodon.social/@harisheoran" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/haris958" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { whatsapp = "https://wa.me/phone-number" },
     { youtube = "https://www.youtube.com/channel/UCkL3XhMfEA46NH57gVSb_Fw" },
#     { ko-fi = "https://ko-fi.com/username" },
      { rss = "https://harisheoran.github.io/index.xml"},

   ]
