[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 30

[[main]]
  name = "logs"
  pageRef = "logs"
  weight = 40

[[main]]
  name = "Work with me"
  url = "https://sparrowbit.github.io/"
  weight = 50

[[main]]
  name = "Resume"
  url = "https://harisheoran.github.io/resume"
  weight = 60

[[main]]
  identifier = "github"
  pre = "github"
  name = "Github"
  url = "https://github.com/harisheoran"
  weight = 400

[[footer]]
  name = "Contact me"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "Blog"
  pageRef = "https://harisheoran.hashnode.dev"

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20
