[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 30

[[main]]
  identifier = "envelope"
  pre = "envelope"
  name = "Contact"
  pageRef = "contact"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/harisheoran"
  weight = 50

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/harisheoran"
  weight = 60

[[main]]
  identifier = "yt"
  pre = "youtube"
  url = "https://www.youtube.com/channel/UCkL3XhMfEA46NH57gVSb_Fw"
  weight = 70

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://linkedin.com/in/harisheoran"
  weight = 80

[[footer]]
  name = "Contact me"
  pre = "envelope"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "Watch Live Streams"
  pre = "youtube"
  url = "https://www.youtube.com/@harisheoran"
  weight = 20

[[footer]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/harisheoran"
  weight = 30

[[footer]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/harisheoran"
  weight = 30

[[footer]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://linkedin.com/in/harisheoran"
  weight = 40

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20
