[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 30

[[main]]
  identifier = "code"
  pre = "youtube"
  name = "Coding"
  pageRef = "coding"
  weight = 40

[[main]]
  identifier = "envelope"
  pre = "envelope"
  name = "Contact"
  pageRef = "contact"
  weight = 50

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/harisheoran"
  weight = 60

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/harisheoran"
  weight = 70

[[footer]]
  name = "Contact me"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "Resume"
  pageRef = "resume"
  weight = 30

[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 40

[[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 50

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20
