[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 30

[[main]]
  name = "Mini Blogs"
  pageRef = "miniblogs"
  weight = 40

[[main]]
  name = "Hire me"
  pageRef = "hire"
  weight = 50

[[main]]
  name = "Resume"
  url = "https://drive.google.com/drive/folders/1IPdGm9x5IiecaWJEzPrvbsXj5Dl3FbZG?usp=sharing"
  weight = 60

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/harisheoran"
  weight = 70

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/harishsheoran01/"
  weight = 70

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/harisheoran"
  weight = 400


[[footer]]
  name = "Contact me"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "Hire me"
  pageRef = "hire"

[[footer]]
  name = "Blog"
  pageRef = "https://harisheoran.hashnode.dev"

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20
