[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "logs"
  pageRef = "logs"
  weight = 40

[[main]]
  name = "Sparrow Bit"
  url = "https://sparrowbit.github.io/"
  weight = 50

[[main]]
  name = "Resume"
  url = "https://drive.google.com/drive/u/0/folders/1IPdGm9x5IiecaWJEzPrvbsXj5Dl3FbZG"
  weight = 60

[[main]]
  name = "Blogs"
  url = "https://harisheoran.hashnode.dev"
  weight = 70

[[main]]
  identifier = "github"
  pre = "github"
  name = "Github"
  url = "https://github.com/harisheoran"
  weight = 400

[[footer]]
  name = "Contact me"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "Blog"
  url = "https://harisheoran.hashnode.dev"
  weight = 20

[[footer]]
  name = "Resume"
  url = "https://drive.google.com/drive/u/0/folders/1IPdGm9x5IiecaWJEzPrvbsXj5Dl3FbZG"
  weight = 30

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20
