[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 10

[[main]]
  identifier = "envelope"
  pre = "envelope"
  name = "Contact"
  pageRef = "contact"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "DevOps"
  pageRef = "devops"
  weight = 50

[[main]]
  identifier = "code"
  pre = "code"
  name = "Coding"
  pageRef = "coding"
  weight = 60

[[main]]
  identifier = "github"
  pre = "github"
  name = "Github"
  url = "https://github.com/harisheoran"
  weight = 80

[[main]]
  identifier = "gitlab"
  pre = "gitlab"
  name = "GitLab"
  url = "https://gitlab.com/harisheoran"
  weight = 90

[[footer]]
  name = "Contact me"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "Blog"
  url = "https://harisheoran.hashnode.dev"
  weight = 20

[[footer]]
  name = "Resume"
  pageRef = "resume"
  weight = 30

[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 40

[[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 50

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20
